busted MMU

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,13 +1,19 @@
 #!/bin/bash
-#/ Usage: script/build
-#/ Build the kernel
+#/ Usage: script/bootstrap
+#/ Installs one-time dependencies.
 source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
 root_dir=$(cd $source_dir && cd ../ && pwd)
 cd $root_dir
 source script/helpers/_utils.sh
 
+if ! type rustup >/dev/null 2>&1; then
+    fatal "rustup not found, please install it from https://rustup.rs/"
+fi
+
 if ! properly_configured; then
     fatal "No configuration found, run 'script/configure' first"
 fi
 
-make
+rustup update
+
+cargo install cargo-binutils
